name: HACS

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
